### ISSUE TITLE
No background + Profile pictures broken

### ISSUE THREAD

**Issue by Rannddy** [mashirochan/Mashiro-chan#8]
[![Screenshot from Gyazo](https://gyazo.com/6e6b10c684a6278da42f0be0d6c6ebea/raw)](https://gyazo.com/6e6b10c684a6278da42f0be0d6c6ebea)

**Comment by mashirochan** [comment]
I did notice that profile pictures were no longer working, thanks for bringing it to my attention - I thought it was just my internet being slow at first! I'll take a look into it and get it fixed ASAP :)

**Comment by Rannddy** [comment]
Sure thing, thanks for the support. Love your theme.

**Comment by mashirochan** [comment]
Should be fixed now! Just had to remove the inline style from the avatars, they changed that for some odd reason. As for your no background issue, my theme isn't meant to have a background, so that's probably why. You need to use my transparency patcher plugin in order to add client transparency and get the most out of my theme!
